# Generated by Django 2.0.7 on 2018-08-01 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achivements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('discription', models.TextField(max_length=4000)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('e_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 4', regex='^.{11}$')])),
            ],
        ),
        migrations.AddField(
            model_name='achivements',
            name='student',
            field=models.ManyToManyField(to='Achievement.Student'),
        ),
    ]
